GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{
    "title": "TypeScript Components",
    "content": "Component-oriented development is much easier using Typescript.",
    "imageUrl": "https://logospng.org/wp-content/uploads/typescript.png",
    "authorId": 1,
    "tags": [
      "typescript",
      "components",
      "frontend"
    ],
    "likeCounter": 0
}
