GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{
    "title": "ReactJS is Easy",
    "content": "Component-Based Build encapsulated components that manage their own state, then compose them to make complex UIs. Since component logic is written in JavaScript instead of templates, you can easily pass rich data through your app and keep state out of the DOM.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    "authorId": 1,
    "tags": [
      "react",
      "spa",
      "intro",
      "frontend"
    ],
    "likeCounter": 0
}
